import "@/styles/globals.css";
import type { AppProps } from "next/app";
// pages/_app.tsx
import { Amplify } from 'aws-amplify';
import config from '@/amplifyconfiguration.json';

// configure the Amplify client library with the configuration generated by `amplify sandbox`
Amplify.configure(config);

export default function App({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}
